import type { Metadata } from "next";
import { ubuntu, ubuntuMono } from "@/@types/font/Font";
import "./globals.css";
import { ThemeProvider } from "@/components/themes/theme-provider";
import Nav from "@/components/webcomp/navigation/Nav";
import { Providers } from "./providers";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<Providers>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange>
						<div>
							<Nav />
						</div>
						<div className={`p-4`}>{children}</div>
					</ThemeProvider>
				</Providers>
			</body>
		</html>
	);
}
